/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swingdeneme;

/**
 *
 * @author Acer
 */
public class Memur extends javax.swing.JFrame {

    /**
     * Creates new form memur
     */
    public Memur() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ogrenciAra = new javax.swing.JButton();
        bosOda = new javax.swing.JButton();
        ogrenciler = new javax.swing.JButton();
        odaKontrol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        ogrenciAra.setBackground(new java.awt.Color(204, 204, 204));
        ogrenciAra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ogrenciAra.setText("ÖĞRENCİ ISLEMLERI");
        ogrenciAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenciAraActionPerformed(evt);
            }
        });

        bosOda.setBackground(new java.awt.Color(204, 204, 204));
        bosOda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bosOda.setText("BOŞ ODA");
        bosOda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosOdaActionPerformed(evt);
            }
        });

        ogrenciler.setBackground(new java.awt.Color(204, 204, 204));
        ogrenciler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ogrenciler.setText("ÖĞENCİLER");
        ogrenciler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrencilerActionPerformed(evt);
            }
        });

        odaKontrol.setBackground(new java.awt.Color(204, 204, 204));
        odaKontrol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        odaKontrol.setText("ODA KONTROL");
        odaKontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odaKontrolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bosOda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ogrenciAra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(odaKontrol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ogrenciler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(odaKontrol)
                .addGap(18, 18, 18)
                .addComponent(ogrenciAra)
                .addGap(20, 20, 20)
                .addComponent(bosOda)
                .addGap(18, 18, 18)
                .addComponent(ogrenciler)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 330, 290));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 447, 397));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odaKontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odaKontrolActionPerformed
        odaKontrol ok= new odaKontrol(); ok.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_odaKontrolActionPerformed

    private void ogrenciAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenciAraActionPerformed
        OgrenciIslem ob=new OgrenciIslem(); ob.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ogrenciAraActionPerformed

    private void bosOdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosOdaActionPerformed
        BosOda bo= new BosOda(); bo.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_bosOdaActionPerformed

    private void ogrencilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrencilerActionPerformed
     Ogrenciler o= new  Ogrenciler(); o.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_ogrencilerActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bosOda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton odaKontrol;
    private javax.swing.JButton ogrenciAra;
    private javax.swing.JButton ogrenciler;
    // End of variables declaration//GEN-END:variables
}
