/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swingdeneme;

/**
 *
 * @author Acer
 */
public class Müdür extends javax.swing.JFrame {

    /**
     * Creates new form Müdür
     */
    public Müdür() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ogrenci = new javax.swing.JButton();
        Personel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        Ogrenci.setBackground(new java.awt.Color(204, 204, 204));
        Ogrenci.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ogrenci.setText("ÖĞRENCİ İŞLEMLERİ");
        Ogrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OgrenciActionPerformed(evt);
            }
        });

        Personel.setBackground(new java.awt.Color(204, 204, 204));
        Personel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Personel.setText("PERSONEL İŞLEMLERİ");
        Personel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ogrenci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Personel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Ogrenci)
                .addGap(37, 37, 37)
                .addComponent(Personel)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OgrenciActionPerformed
Memur m =new Memur(); m.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OgrenciActionPerformed

    private void PersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonelActionPerformed
PersonelIslemleri pi=new PersonelIslemleri(); pi.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonelActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ogrenci;
    private javax.swing.JButton Personel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
